# Generated by Django 4.2.8 on 2026-02-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'CV Education',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CVStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_scholar_citations', models.CharField(default='239+', max_length=50)),
                ('h_index', models.CharField(default='H-8', max_length=50)),
                ('publications', models.CharField(default='50+', max_length=50)),
                ('patents', models.CharField(default='9+', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'CV Statistics',
            },
        ),
    ]
